### PR TITLE
Resolve Link Issues

### PR DESCRIPTION
**Pull request by ben9583**
Remake links referencing the 2021-spring website to point to the archive as opposed to the live site.

### CODE REVIEW

**Comment by ben9583** [comment]
@64bitpandas How do you feel about 'a' tags referencing https://decal.ocf.berkeley.edu/archives/2021-spring? Or should I just use relative paths where applicable

**Comment by 64bitpandas** [comment]
> @64bitpandas How do you feel about 'a' tags referencing https://decal.ocf.berkeley.edu/archives/2021-spring? Or should I just use relative paths where applicable

I don't think it matters too much either way. The main goal is to ensure the archived content doesn't get affected by changes to master, so as long as this is the case it should be good!

**Comment by ben9583** [comment]
Alright, nice. I didn't touch links that go to https://decal.ocf.berkeley.edu/static since that folder wasn't present in 2021-spring. If that's ok, this pr should be all good.

**Review by 64bitpandas — APPROVED** [review]
This looks great, thank you! I will deploy and let you know how it goes

**Comment by 64bitpandas** [comment]
It should be deployed now, feel free to play around and make sure all the links are pointing to the right place

**Pull request merged**
